version: '3.7'
services:
  client:
    build:
      context: ./web/client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    image: dkushnir/templater:node-client
    container_name: 'Client'
    volumes:
      - ./web/client:/app
    command: 'npm run start'
    networks:
      - templater-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

  server:
    build:
      context: ./web/server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - '9229:9229'
    image: dkushnir/templater:node-server
    container_name: 'Server'
    volumes:
      - ./web/server:/app
    command: 'npm run start-reload'
    networks:
      - templater-network
    environment:
      PORT: 8080
      NODE_ENV: 'docker-local'

networks:
    templater-network:
      driver: bridge
